import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// Generated by doc-driven-dev (/docs-site init). Reads the docs/ tree one level up.
// The validator (docs-tools/check-docs.mjs) is the hard link gate; this build warns.
const config: Config = {
  title: "doc-driven-dev docs",
  tagline: "Documentation for doc-driven-dev",

  url: "https://sh4pesh1fter.github.io",
  baseUrl: "/doc-driven-dev/",

  organizationName: "Sh4peSh1fter",
  projectName: "doc-driven-dev",

  // Content links are hard-gated by the validator (docs-tools/check-docs.mjs). Here we
  // warn rather than throw, because docs intentionally link to excluded areas (_templates/).
  // Anchors stay strict — those always point at built pages.
  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",
  onBrokenAnchors: "throw",

  i18n: { defaultLocale: "en", locales: ["en"] },

  presets: [
    [
      "classic",
      {
        docs: {
          // The docs live in the repo's docs/ folder, one level above this site.
          path: "../docs",
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          // Exclude non-published material. This custom list REPLACES Docusaurus's default
          // exclude (which would drop every underscore dir, including _standards/), so the
          // standards pages publish while templates, assets, trackers, and the archive do not.
          exclude: [
            "**/_*.{md,mdx}",
            "**/_tasks/**",
            "**/_templates/**",
            "**/_assets/**",
            "99-archive/**",
          ],
          editUrl: "https://github.com/Sh4peSh1fter/doc-driven-dev/edit/main/",
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: "doc-driven-dev",
      items: [
        { type: "docSidebar", sidebarId: "docs", position: "left", label: "Docs" },
        { href: "https://github.com/Sh4peSh1fter/doc-driven-dev", label: "GitHub", position: "right" },
      ],
    },
    footer: {
      style: "dark",
      links: [],
      copyright: "Docs built with doc-driven-dev.",
    },
    prism: {},
  } satisfies Preset.ThemeConfig,
};

export default config;
