import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Autogenerated sidebar: Docusaurus builds the tree from the docs/ folder structure
// and each folder's _category_.json (generated by /docs-site init per enabled section).
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
